apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: jvm-build-suite-component-ligbvp
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: jvm-build-suite-component-ligbvp
    app.kubernetes.io/part-of: jvm-build-suite-application-pose
  name: jvm-build-suite-component-ligbvp
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: jvm-build-suite-component-ligbvp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: jvm-build-suite-component-ligbvp
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/jvm-build-etkb-tenant/jvm-build-suite-application-pose/jvm-build-suite-component-ligbvp@sha256:5ba64320a8fa6d0e332f0f6fec926f85cdfb85d71928e322554e1e9c68952538
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
